import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';

import { getLanguage, setLanguage as setLanguageStorage } from './storage';

const TRADUCOES = {
  pt: {
    'comum.usuario': 'Usuário',
    'comum.cancelar': 'Cancelar',
    'comum.descartar': 'Descartar',
    'comum.entrar': 'Entrar',
    'comum.criarConta': 'Criar conta',
    'comum.erro': 'Erro',
    'comum.erroSalvarDados': 'Não foi possível salvar seus dados. Tente novamente.',
    'comum.avancar': 'Avançar',
    'comum.evolucaoDiaria': 'Evolução diária',
    'comum.ranking': 'Ranking',
    'comum.abrirRanking': 'Abrir ranking',

    'tipo.NORMAL': 'Série',
    'tipo.AQUECIMENTO': 'Aquecimento',
    'tipo.PREPARATORIA': 'Preparatória',
    'tipo.RECONHECIMENTO': 'Reconhecimento',
    'tipo.BACK_OFF': 'Back-off set',
    'tipo.DROPSET': 'Dropset',
    'tipo.FALHA': 'Falha',

    'sessaoAtiva.tag': 'SESSÃO ATIVA',
    'sessaoAtiva.semTitulo': 'Sessão Ativa',
    'sessaoAtiva.concluir': 'Concluir',
    'sessaoAtiva.colSerie': 'Série',
    'sessaoAtiva.colKg': 'Kg',
    'sessaoAtiva.colReps': 'Reps',
    'sessaoAtiva.colNotas': 'Notas',
    'sessaoAtiva.acessibilidadeBadge': 'Alterar tipo ou remover série',
    'sessaoAtiva.descartarTreino': 'Descartar Treino',
    'sessaoAtiva.confirmarDescartar': 'Tem certeza de que deseja descartar este treino? As séries serão perdidas.',
    'sessaoAtiva.menuSubtitulo': 'Escolha o tipo ou remova esta série',
    'sessaoAtiva.removerSerie': 'Remover série',
    'sessaoAtiva.treinoConcluido': 'Treino concluído',
    'sessaoAtiva.salvoHistorico': 'Seu treino foi salvo no histórico local.',
    'sessaoAtiva.erroSalvar': 'Não foi possível salvar o treino localmente.',
    'sessaoAtiva.serieLabel': 'Série',
    'sessaoAtiva.adicionarSerie': 'Série',
    'sessaoAtiva.notaPlaceholder': 'Adicionar notas...',
    'sessaoAtiva.cancelar': 'Cancelar',
    'sessaoAtiva.treinoVazio': 'Treino vazio',
    'sessaoAtiva.treinoVazioMsg': 'Adicione ao menos uma série antes de concluir o treino.',

    'novaSessao.usarSessao': 'Usar sessão criada',
    'novaSessao.titulo': 'Título da sessão',
    'novaSessao.placeholderTitulo': 'Adicionar título...',

    'treinoHub.sessaoTreino': 'Sessão de Treino',
    'treinoHub.iniciar': 'Iniciar treino',
    'treinoHub.criar': 'Criar sessão de treino',

    'nav.treino': 'Treino',
    'nav.alimentacao': 'Alimentação',
    'nav.relogio': 'Relógio',

    'cadastro.titulo': 'Crie sua conta',
    'cadastro.subtitulo': 'Comece sua jornada com o GymVance',
    'cadastro.email': 'E-mail',
    'cadastro.senha': 'Senha',
    'cadastro.confirmarSenha': 'Confirmar senha',
    'cadastro.erroEmail': 'Insira um e-mail válido.',
    'cadastro.erroSenhaCurta': 'A senha deve ter pelo menos 6 caracteres.',
    'cadastro.erroSenhasDiferentes': 'As senhas não são iguais.',
    'cadastro.jaTemConta': 'Já tem uma conta?',

    'entrar.titulo': 'Bem-vindo de volta!',
    'entrar.subtitulo': 'Entre na sua conta do GymVance',
    'entrar.aindaNaoTemConta': 'Ainda não tem uma conta?',
    'entrar.erroCredenciais': 'E-mail ou senha incorretos. Verifique suas credenciais.',

    // Autenticação social / por provedor (pt).
    // IMPORTANTE: essas opções NÃO estão implementadas neste build (não há
    // backend, SDK de OAuth, app-id ou client-id configurados). Elas são
    // renderizadas para preparar a interface, mas NUNCA criam conta nem
    // sessão - exibem aviso honesto informando que exigem configuração
    // externa. Nenhuma credencial ou token é gerado/inventado.
    'auth.ouContinueCom': 'ou continue com',
    'auth.google': 'Continuar com Google',
    'auth.facebook': 'Continuar com Facebook',
    'auth.apple': 'Continuar com Apple',
    'auth.email': 'Continuar com E-mail',
    'auth.telefone': 'Continuar com Telefone',
    'auth.googleIndisponivel': 'Google ainda não configurado',
    'auth.googleMsg': 'O login com Google exige um Client ID do Google Cloud e um backend de autenticação, que ainda não foram configurados neste build. Por isso, não é possível concluir um login real agora (sem contas falsas).',
    'auth.facebookIndisponivel': 'Facebook ainda não configurado',
    'auth.facebookMsg': 'O login com Facebook exige um App ID do Facebook Developer e um backend de autenticação, que ainda não foram configurados neste build. A opção está preparada, mas não conclui login real (sem contas falsas).',
    'auth.appleIndisponivel': 'Apple ainda não configurado',
    'auth.appleMsg': 'O login com Apple (Sign in with Apple) exige configuração no Apple Developer (App ID / Service ID) e backend. Não está configurado neste build.',
    'auth.emailMsg': 'E-mail e senha funcionam localmente neste aplicativo. Esta é a forma de acesso ativa.',
    'auth.telefoneIndisponivel': 'Telefone ainda não configurado',
    'auth.telefoneMsg': 'O login por telefone exige um serviço de SMS/OTP com backend, que não está configurado. Por isso não simulamos um código de verificação falso.',
    'auth.notaProvedores': 'Os botões de provedor exibem um aviso honesto quando o login externo ainda não está configurado neste build. Nenhum deles cria conta falsa nem sessão inventada.',

    'peso.etapa': 'Etapa 2 de 4',
    'peso.titulo': 'Qual seu peso?',
    'peso.obrigatorio': 'Peso obrigatório',
    'peso.erroValor': 'Informe um peso válido para continuar.',

    'altura.etapa': 'Etapa 3 de 4',
    'altura.titulo': 'Qual sua altura?',
    'altura.nome': 'Altura',
    'altura.obrigatoria': 'Altura obrigatória',
    'altura.erroValor': 'Informe uma altura válida para continuar.',

    'genero.etapa': 'Etapa 4 de 4',
    'genero.titulo': 'Crie seu perfil',
    'genero.nome': 'Nome',
    'genero.placeholderNome': 'Digite seu nome',
    'genero.genero': 'Gênero',
    'genero.homem': 'Homem',
    'genero.mulher': 'Mulher',
    'genero.helperGenero': 'Usamos o gênero para adaptar o volume de treino, gasto calórico e dieta.',
    'genero.dataNascimento': 'Data de nascimento',
    'genero.placeholderData': 'DD/MM/AAAA',
    'genero.helperData': 'Informe a data completa do seu nascimento para personalizar sua evolução.',
    'genero.erroNome': 'Nome obrigatório',
    'genero.erroNomeMsg': 'Informe seu nome para continuar.',
    'genero.erroData': 'Data inválida',
    'genero.erroDataMsg': 'Informe uma data de nascimento válida no formato DD/MM/AAAA.',
    'genero.erroGenero': 'Gênero obrigatório',
    'genero.erroGeneroMsg': 'Selecione seu gênero para continuar.',

    'perfil.idioma': 'Idioma',
    'perfil.portugues': 'Português',
    'perfil.ingles': 'English',
    'perfil.meuPerfil': 'Meu Perfil',
    'perfil.treinosConcluidos': 'Treinos concluídos',
    'perfil.series': 'Séries',
    'perfil.tempoTotal': 'Tempo total',
    'perfil.salvarAlteracoes': 'Salvar alterações',
    'perfil.minhaEvolucao': 'Minha Evolução',
    'perfil.subtitulo': 'Acompanhe suas fotos e evolução corporal',
    'perfil.antes': 'ANTES',
    'perfil.depois': 'DEPOIS',
    'perfil.adicionarFoto': 'Adicionar Foto',
    'perfil.medidasRecentes': 'Medidas Recentes',
    'perfil.medida.peso': 'Peso',
    'perfil.medida.cintura': 'Cintura',
    'perfil.medida.braco': 'Braço',
    'perfil.medida.peito': 'Peito',
    'perfil.editarPerfil': 'Editar Perfil',
    'perfil.historico': 'Histórico',
    'perfil.foto': 'foto',
    'perfil.fotos': 'fotos',
    'perfil.registrada': 'registrada',
    'perfil.registradas': 'registradas',
    'perfil.nomeLabel': 'Nome',
    'perfil.placeholderNome': 'Digite seu nome',
    'perfil.emailLabel': 'Email',
    'perfil.placeholderEmail': 'Digite seu email',
    'perfil.galeriaBloqueada': 'Galeria bloqueada',
    'perfil.galeriaBloqueadaMsg': 'Permita o acesso às fotos nas configurações para registrar seu progresso.',
    'perfil.abrirConfiguracoes': 'Abrir configurações',
    'perfil.permissaoNecessaria': 'Permissão necessária',
    'perfil.fotosPermissaoMsg': 'Precisamos acessar suas fotos para registrar seu progresso.',
    'perfil.erroAdicionarFoto': 'Não foi possível adicionar a foto.',
    'perfil.erroSalvarPerfil': 'Não foi possível salvar suas alterações.',
    'perfil.fecharFoto': 'Fechar foto',
    'perfil.voltar': 'Voltar',

    'configuracoes.titulo': 'Configurações',
    'configuracoes.idioma': 'Idioma',
    'configuracoes.plano': 'Meu Plano',
    'configuracoes.semPlano': 'Nenhum plano selecionado',
    'configuracoes.verPlanos': 'Ver planos',
    'configuracoes.sair': 'Sair da conta',
    'configuracoes.sairMsg': 'Deseja sair da conta?',
    'configuracoes.confirmarSair': 'Sair',

    'ranking.geral': 'Ranking Geral',
    'ranking.subtitulo': 'Supere seus limites e conquiste o topo!',
    'ranking.semanal': 'Semanal',
    'ranking.mensal': 'Mensal',
    'ranking.todas': 'Geral',
    'ranking.dias': 'dias',
    'ranking.voce': 'VOCÊ',
    'ranking.treinos': 'treinos concluídos',
    'ranking.vazioTitulo': 'Ranking ainda não está disponível',
    'ranking.vazioTexto': 'Volte mais tarde para acompanhar sua posição.',

    'alimentacao.consumoDiario': 'Consumo Diário',
    'alimentacao.refeicoesHoje': 'Refeições de hoje',
    'alimentacao.minhasFotos': 'Minhas fotos',
    'alimentacao.semFotos': 'Nenhuma foto salva ainda.',
    'alimentacao.abasFotos': 'Fotos',
    'alimentacao.abasAlbuns': 'Álbuns',
    'alimentacao.abasHistorias': 'Histórias',
    'alimentacao.abasMais': 'Mais',
    'alimentacao.permissaoTitulo': 'Permissão necessária',
    'alimentacao.permissaoMsg': 'Precisamos acessar suas fotos para salvar seu progresso.',
    'alimentacao.erroSalvarFoto': 'Não foi possível salvar a foto.',
    'alimentacao.cameraIndisponivel': 'Câmera indisponível',
    'alimentacao.cameraMsg': 'Abra as configurações do dispositivo para permitir o acesso à câmera.',
    'alimentacao.cameraPermMsg': 'Precisamos da câmera para registrar sua refeição.',
    'alimentacao.erroCapturar': 'Não foi possível capturar a imagem.',

    'batimento.aguardando': 'Aguardando...',
    'batimento.altaPrecisao': '🟢 Alta precisão',
    'batimento.mediaPrecisao': '🟡 Média precisão',
    'batimento.baixaPrecisao': '🔴 Baixa precisão',
    'batimento.queimaDiaria': 'QUEIMA DIÁRIA',
    'batimento.localizacao': 'LOCALIZAÇÃO',
    'batimento.atualizar': 'Atualizar',
    'batimento.buscando': 'Buscando...',
    'batimento.precisao': 'Precisão:',
    'batimento.precisaoAnalise': 'Precisão em análise',
    'batimento.erroBloqueadoTitulo': 'Localização bloqueada',
    'batimento.erroBloqueadoMsg': 'Abra as configurações do aparelho para permitir o uso do GPS.',
    'batimento.erroPermissao': 'Permissão de localização negada.',
    'batimento.erroGps': 'GPS desativado. Ative a localização para continuar.',
    'batimento.erroObter': 'Não foi possível obter a localização agora.',

    'calorias.batimentoCardiaco': 'BATIMENTO CARDÍACO',
    'calorias.normal': 'Normal',
    'calorias.de': 'de',

    'mensal.mensal': 'Mensal',
    'mensal.anual': 'Anual',
    'mensal.eterno': 'Eterno',
    'mensal.cobradoMensalmente': 'Cobrado mensalmente',
    'mensal.cobradoAnualmente': 'Cobrado Anualmente',
    'mensal.compraUnica': 'Compra única',
    'mensal.benef1Titulo': 'Rotinas ilimitadas',
    'mensal.benef1Desc': 'Crie a rotina que quiser',
    'mensal.benef2Titulo': '10 tokens de IA todos os dias',
    'mensal.benef2Desc': 'Monte treinos com ajuda da inteligência artificial',
    'mensal.benef3Titulo': 'Estatísticas avançadas',
    'mensal.benef3Desc': 'Acompanhe sua evolução em detalhes',
    'mensal.benef4Titulo': 'Apoie nossa equipe',
    'mensal.benef4Desc': 'Ajude o GymVance a continuar evoluindo',
    'mensal.assinar': 'Assinar',
    'mensal.agoraNao': 'Agora não',
    'mensal.ativadoTitulo': 'Plano PRO ativado',
    'mensal.ativadoMsg': 'Seu plano {plano} foi selecionado com sucesso.',
    'mensal.erroAtivar': 'Não foi possível ativar o plano no momento.',

    'configuracoes.perfil': 'Perfil',
    'configuracoes.conta': 'Conta',
    'configuracoes.unidade': 'Unidade',
    'configuracoes.faq': 'Perguntas frequentes',
    'configuracoes.avaliar': 'Avaliar aplicativo',
    'configuracoes.treinos': 'Treinos',
    'configuracoes.pro': 'PRO',
    'configuracoes.versao': 'Versão',

    'perfil.seguidores': 'Seguidores',
    'perfil.seguindo': 'Seguindo',
    'perfil.estatisticas': 'Estatísticas',
    'perfil.exercicios': 'Exercícios',
    'perfil.medidas': 'Medidas',
    'perfil.calendario': 'Calendário',
    'perfil.bio': 'Bio',
    'perfil.idade': 'Idade',
    'configuracoes.perfilTitulo': 'Configurações do Perfil',

    'editarPerfil.titulo': 'Editar Perfil',
    'editarPerfil.nome': 'Nome',
    'editarPerfil.placeholderNome': 'Digite seu nome',
    'editarPerfil.bio': 'Bio',
    'editarPerfil.placeholderBio': 'Conte algo sobre você',
    'editarPerfil.genero': 'Gênero',
    'editarPerfil.idade': 'Idade',
    'editarPerfil.foto': 'Foto do perfil',
    'editarPerfil.alterarFoto': 'Alterar foto',
    'editarPerfil.removerFoto': 'Remover foto',
    'editarPerfil.salvar': 'Salvar alterações',

    'conta.titulo': 'Conta',
    'conta.nome': 'Nome',
    'conta.email': 'E-mail',
    'conta.senha': 'Senha',
    'conta.novaSenha': 'Nova senha',
    'conta.confirmarSenha': 'Confirmar nova senha',
    'conta.senhaAtual': 'Senha atual',
    'conta.alterarSenha': 'Alterar senha',
    'conta.salvar': 'Salvar alterações',
    'conta.erroSenhaAtual': 'Senha atual incorreta',
    'conta.erroSenhasDiferentes': 'As novas senhas não coincidem',
    'conta.erroSenhaCurta': 'A nova senha deve ter pelo menos 6 caracteres',
    'conta.sucesso': 'Alterações salvas com sucesso',

    'unidade.titulo': 'Unidade de Medida',
    'unidade.peso': 'Peso',
    'unidade.altura': 'Altura',
    'unidade.kg': 'kg',
    'unidade.lb': 'lb',
    'unidade.cm': 'cm',
    'unidade.ft': 'ft/in',

    'faq.titulo': 'Perguntas Frequentes',
    'faq.categoria.conta': 'Conta e Perfil',
    'faq.categoria.treinos': 'Treinos',
    'faq.categoria.pro': 'PRO',
    'faq.categoria.idioma': 'Idioma e Unidades',
    'faq.categoria.app': 'Funcionamento do App',
    'faq.pergunta1': 'Como altero meu nome ou foto de perfil?',
    'faq.resposta1': 'Vá em Configurações > Perfil e toque na foto ou no botão Editar Perfil.',
    'faq.pergunta2': 'Como mudo meu e-mail ou senha?',
    'faq.resposta2': 'Vá em Configurações > Conta para alterar seus dados de acesso.',
    'faq.pergunta3': 'Meus treinos são salvos automaticamente?',
    'faq.resposta3': 'Sim, ao concluir uma sessão em "Sessão Ativa", o treino é salvo no histórico local.',
    'faq.pergunta4': 'Como funciona o plano PRO?',
    'faq.resposta4': 'O plano PRO desbloqueia rotinas ilimitadas, tokens de IA diários, estatísticas avançadas e apoia o desenvolvimento do app.',
    'faq.pergunta5': 'Como mudo o idioma do aplicativo?',
    'faq.resposta5': 'Vá em Configurações > Idioma e selecione Português ou English.',
    'faq.pergunta6': 'Posso usar libras (lb) em vez de kg?',
    'faq.resposta6': 'Sim, em Configurações > Unidade você altera a preferência de peso e altura.',
    'faq.pergunta7': 'O app funciona offline?',
    'faq.resposta7': 'Sim, todos os dados são salvos localmente no seu dispositivo.',
    'faq.pergunta8': 'Como entro em contato com o suporte?',
    'faq.resposta8': 'Envie um e-mail para suporte@gymvance.com',

    'avaliar.titulo': 'Avaliar Aplicativo',
    'avaliar.subtitulo': 'Sua opinião nos ajuda a melhorar o GymVance',
    'avaliar.botao': 'Avaliar na Play Store',
    'avaliar.obrigado': 'Obrigado por avaliar!',
    'avaliar.erro': 'Não foi possível abrir a loja. Tente novamente mais tarde.',

    'treinos.titulo': 'Meus Treinos',
    'treinos.irParaTreino': 'Ir para área de treino',

    'exercicios.titulo': 'Catálogo de Exercícios',
    'exercicios.pesquisar': 'Pesquisar exercício...',
    'exercicios.categoria.maquinas': 'Máquinas',
    'exercicios.categoria.cabos': 'Cabos / Polias',
    'exercicios.categoria.pesosLivres': 'Pesos Livres',
    'exercicios.categoria.pesoCorporal': 'Peso Corporal / Livres',
    'exercicios.categoria.personalizados': 'Personalizados',

    'exercicios.grupo.peito': 'Peito',
    'exercicios.grupo.costas': 'Costas',
    'exercicios.grupo.ombros': 'Ombros',
    'exercicios.grupo.biceps': 'Bíceps',
    'exercicios.grupo.triceps': 'Tríceps',
    'exercicios.grupo.pernas': 'Pernas',
    'exercicios.grupo.gluteos': 'Glúteos',
    'exercicios.grupo.panturrilhas': 'Panturrilhas',
    'exercicios.grupo.abdomen': 'Abdômen',
    'exercicios.grupo.corpointeiro': 'Corpo Inteiro',

    'exercicios.oficial': 'Oficial',
    'exercicios.personalizado': 'Personalizado',
    'exercicios.criarPersonalizado': '+ Criar exercício personalizado',
    'exercicios.semResultados': 'Nenhum exercício encontrado',
    'exercicios.adicionar': 'Adicionar à sessão',
    'exercicios.selecionarGrupo': 'Selecione um grupo muscular',
    'exercicios.editarTitulo': 'Editar exercício personalizado',
    'exercicios.editar': 'Editar',
    'exercicios.excluir': 'Excluir',
    'exercicios.excluirTitulo': 'Excluir exercício',
    'exercicios.excluirMsg': 'Deseja excluir este exercício personalizado? Essa ação não pode ser desfeita.',

    'calendario.titulo': 'Calendário de Treinos',
    'calendario.verCalendario': 'Ver calendário',
    'calendario.treinosMes': '{treinos} treinos neste mês',
    'calendario.semTreinosMes': 'Nenhum treino neste mês',
    'calendario.semTreinosDia': 'Nenhum treino neste dia',
    'calendario.mesAnterior': 'Mês anterior',
    'calendario.proximoMes': 'Próximo mês',
    'calendario.exercicios': '{count} exercícios',
    'calendario.diaSemana.0': 'D',
    'calendario.diaSemana.1': 'S',
    'calendario.diaSemana.2': 'T',
    'calendario.diaSemana.3': 'Q',
    'calendario.diaSemana.4': 'Q',
    'calendario.diaSemana.5': 'S',
    'calendario.diaSemana.6': 'S',
    'calendario.mes.0': 'Janeiro',
    'calendario.mes.1': 'Fevereiro',
    'calendario.mes.2': 'Março',
    'calendario.mes.3': 'Abril',
    'calendario.mes.4': 'Maio',
    'calendario.mes.5': 'Junho',
    'calendario.mes.6': 'Julho',
    'calendario.mes.7': 'Agosto',
    'calendario.mes.8': 'Setembro',
    'calendario.mes.9': 'Outubro',
    'calendario.mes.10': 'Novembro',
    'calendario.mes.11': 'Dezembro',

    'sessaoAtiva.retomarTitulo': 'Treino em andamento',
    'sessaoAtiva.retomarMsg': 'Há uma sessão de treino não concluída salva neste dispositivo. Deseja continuar de onde parou?',
    'sessaoAtiva.continuarTreino': 'Continuar treino',
    'sessaoAtiva.comecarNovo': 'Começar nova sessão',

    'perfil.ofensiva': 'Ofensiva',

    'perfil.exerciciosUnicos': 'Exercícios únicos realizados',
    'perfil.calendarioEmBreve': 'Calendário de treinos em breve',
    'comum.anos': 'anos',
    'exercicios.grupoMuscular': 'Grupo Muscular',
    'exercicios.equipamento': 'Equipamento',
    'novaSessao.adicionarExercicio': 'Adicionar Exercício',
    'novaSessao.exerciciosDaSessao': 'Exercícios da Sessão',
    'novaSessao.erroSemExercicios': 'Adicione ao menos um exercício',
    'novaSessao.erroSemTitulo': 'Adicione um título à sessão',
    'novaSessao.iniciarTreino': 'Iniciar Treino',
    'exercicios.equipamentoPlaceholder': 'Ex: Halteres, Máquina, Peso Corporal',
    'exercicios.equipamento.maquina': 'Máquina',
    'exercicios.equipamento.cabo': 'Cabo',
    'exercicios.equipamento.barra': 'Barra',
    'exercicios.equipamento.halteres': 'Halteres',
    'exercicios.equipamento.halter': 'Halter',
    'exercicios.equipamento.pesoCorporal': 'Peso Corporal',
    'exercicios.equipamento.paralelas': 'Paralelas',
    'exercicios.equipamento.personalizado': 'Personalizado',
  },
  en: {
    'comum.usuario': 'User',
    'comum.cancelar': 'Cancel',
    'comum.descartar': 'Discard',
    'comum.entrar': 'Sign in',
    'comum.criarConta': 'Create account',
    'comum.erro': 'Error',
    'comum.erroSalvarDados': 'Could not save your data. Please try again.',
    'comum.avancar': 'Continue',
    'comum.evolucaoDiaria': 'Daily progress',
    'comum.ranking': 'Ranking',
    'comum.abrirRanking': 'Open ranking',

    'tipo.NORMAL': 'Set',
    'tipo.AQUECIMENTO': 'Warm-up',
    'tipo.PREPARATORIA': 'Preparation',
    'tipo.RECONHECIMENTO': 'Recognition',
    'tipo.BACK_OFF': 'Back-off set',
    'tipo.DROPSET': 'Dropset',
    'tipo.FALHA': 'Failure',

    'sessaoAtiva.tag': 'ACTIVE SESSION',
    'sessaoAtiva.semTitulo': 'Active Session',
    'sessaoAtiva.concluir': 'Finish',
    'sessaoAtiva.colSerie': 'Set',
    'sessaoAtiva.colKg': 'Kg',
    'sessaoAtiva.colReps': 'Reps',
    'sessaoAtiva.colNotas': 'Notes',
    'sessaoAtiva.acessibilidadeBadge': 'Change set type or remove set',
    'sessaoAtiva.descartarTreino': 'Discard Workout',
    'sessaoAtiva.confirmarDescartar': 'Are you sure you want to discard this workout? Your sets will be lost.',
    'sessaoAtiva.menuSubtitulo': 'Choose the set type or remove this set',
    'sessaoAtiva.removerSerie': 'Remove set',
    'sessaoAtiva.treinoConcluido': 'Workout completed',
    'sessaoAtiva.salvoHistorico': 'Your workout was saved to the local history.',
    'sessaoAtiva.erroSalvar': 'Could not save the workout locally.',
    'sessaoAtiva.serieLabel': 'Set',
    'sessaoAtiva.adicionarSerie': 'Set',
    'sessaoAtiva.notaPlaceholder': 'Add notes...',
    'sessaoAtiva.cancelar': 'Cancel',
    'sessaoAtiva.treinoVazio': 'Empty workout',
    'sessaoAtiva.treinoVazioMsg': 'Add at least one set before finishing the workout.',

    'novaSessao.usarSessao': 'Use created session',
    'novaSessao.titulo': 'Session title',
    'novaSessao.placeholderTitulo': 'Add a title...',

    'treinoHub.sessaoTreino': 'Workout Session',
    'treinoHub.iniciar': 'Start workout',
    'treinoHub.criar': 'Create workout session',

    'nav.treino': 'Workout',
    'nav.alimentacao': 'Food',
    'nav.relogio': 'Clock',

    'cadastro.titulo': 'Create your account',
    'cadastro.subtitulo': 'Start your journey with GymVance',
    'cadastro.email': 'Email',
    'cadastro.senha': 'Password',
    'cadastro.confirmarSenha': 'Confirm password',
    'cadastro.erroEmail': 'Enter a valid email.',
    'cadastro.erroSenhaCurta': 'The password must have at least 6 characters.',
    'cadastro.erroSenhasDiferentes': 'Passwords do not match.',
    'cadastro.jaTemConta': 'Already have an account?',

    'entrar.titulo': 'Welcome back!',
    'entrar.subtitulo': 'Sign in to your GymVance account',
    'entrar.aindaNaoTemConta': "Don't have an account yet?",
    'entrar.erroCredenciais': 'Email or password is incorrect. Check your credentials.',

    // Social / provider sign-in options (EN).
    // These buttons are UI-prep only. No Google/Facebook/Apple OAuth SDK,
    // OAuth client/App IDs, SMS/OTP gateway or backend are configured in
    // this build, so tapping them never creates a real session and never
    // invents credentials — they show an honest "not configured" message.
    'auth.google': 'Continue with Google',
    'auth.facebook': 'Continue with Facebook',
    'auth.apple': 'Continue with Apple',
    'auth.email': 'Continue with Email',
    'auth.telefone': 'Continue with Phone',
    'auth.ouContinueCom': 'or continue with',
    'auth.emailMsg': 'Email and password work locally in this app. This is the active sign-in method.',
    'auth.googleIndisponivel': 'Google not configured yet',
    'auth.googleMsg': 'Sign in with Google requires a Google Cloud Client ID and an authentication backend, which are not configured in this build. That is why this option can\'t complete a real login right now (no fake accounts).',
    'auth.facebookIndisponivel': 'Facebook not configured yet',
    'auth.facebookMsg': 'Sign in with Facebook requires a Facebook Developer App ID and an authentication backend, which are not configured in this build. That is why this option can\'t complete a real login right now (no fake accounts).',
    'auth.appleIndisponivel': 'Apple not configured yet',
    'auth.appleMsg': 'Sign in with Apple requires an Apple Developer App ID / Service ID and an authentication backend, which are not configured in this build. That is why this option can\'t complete a real login right now (no fake accounts).',
    'auth.telefoneIndisponivel': 'Phone not configured yet',
    'auth.telefoneMsg': 'Sign in with phone requires an SMS/OTP gateway and an authentication backend, which are not configured in this build. That is why this option can\'t send a real verification code (no fake codes).',
    'auth.notaProvedores': 'The provider buttons show an honest notice when external sign-in is not configured in this build. None of them creates a fake account or an invented session.',

    'peso.etapa': 'Step 2 of 4',
    'peso.titulo': "What's your weight?",
    'peso.obrigatorio': 'Weight required',
    'peso.erroValor': 'Enter a valid weight to continue.',

    'altura.etapa': 'Step 3 of 4',
    'altura.titulo': "What's your height?",
    'altura.nome': 'Height',
    'altura.obrigatoria': 'Height required',
    'altura.erroValor': 'Enter a valid height to continue.',

    'genero.etapa': 'Step 4 of 4',
    'genero.titulo': 'Create your profile',
    'genero.nome': 'Name',
    'genero.placeholderNome': 'Type your name',
    'genero.genero': 'Gender',
    'genero.homem': 'Man',
    'genero.mulher': 'Woman',
    'genero.helperGenero': 'We use gender to adapt workout volume, calorie burn and diet.',
    'genero.dataNascimento': 'Date of birth',
    'genero.placeholderData': 'DD/MM/YYYY',
    'genero.helperData': 'Enter your full birth date to personalize your progress.',
    'genero.erroNome': 'Name required',
    'genero.erroNomeMsg': 'Enter your name to continue.',
    'genero.erroData': 'Invalid date',
    'genero.erroDataMsg': 'Enter a valid birth date in DD/MM/YYYY format.',
    'genero.erroGenero': 'Gender required',
    'genero.erroGeneroMsg': 'Select your gender to continue.',

    'perfil.idioma': 'Language',
    'perfil.portugues': 'Português',
    'perfil.ingles': 'English',
    'perfil.meuPerfil': 'My Profile',
    'perfil.treinosConcluidos': 'Workouts completed',
    'perfil.series': 'Sets',
    'perfil.tempoTotal': 'Total time',
    'perfil.salvarAlteracoes': 'Save changes',
    'perfil.minhaEvolucao': 'My Progress',
    'perfil.subtitulo': 'Track your photos and body progress',
    'perfil.antes': 'BEFORE',
    'perfil.depois': 'AFTER',
    'perfil.adicionarFoto': 'Add Photo',
    'perfil.medidasRecentes': 'Recent Measurements',
    'perfil.medida.peso': 'Weight',
    'perfil.medida.cintura': 'Waist',
    'perfil.medida.braco': 'Arm',
    'perfil.medida.peito': 'Chest',
    'perfil.editarPerfil': 'Edit Profile',
    'perfil.historico': 'History',
    'perfil.foto': 'photo',
    'perfil.fotos': 'photos',
    'perfil.registrada': 'registered',
    'perfil.registradas': 'registered',
    'perfil.nomeLabel': 'Name',
    'perfil.placeholderNome': 'Type your name',
    'perfil.emailLabel': 'Email',
    'perfil.placeholderEmail': 'Type your email',
    'perfil.galeriaBloqueada': 'Gallery blocked',
    'perfil.galeriaBloqueadaMsg': 'Allow photo access in settings to record your progress.',
    'perfil.abrirConfiguracoes': 'Open settings',
    'perfil.permissaoNecessaria': 'Permission required',
    'perfil.fotosPermissaoMsg': 'We need access to your photos to record your progress.',
    'perfil.erroAdicionarFoto': 'Could not add the photo.',
    'perfil.erroSalvarPerfil': 'Could not save your changes.',
    'perfil.fecharFoto': 'Close photo',
    'perfil.voltar': 'Back',

    'configuracoes.titulo': 'Settings',
    'configuracoes.idioma': 'Language',
    'configuracoes.plano': 'My Plan',
    'configuracoes.semPlano': 'No plan selected',
    'configuracoes.verPlanos': 'View plans',
    'configuracoes.sair': 'Sign out',
    'configuracoes.sairMsg': 'Do you want to sign out?',
    'configuracoes.confirmarSair': 'Sign out',

    'ranking.geral': 'General Ranking',
    'ranking.subtitulo': 'Push your limits and reach the top!',
    'ranking.semanal': 'Weekly',
    'ranking.mensal': 'Monthly',
    'ranking.todas': 'All',
    'ranking.dias': 'days',
    'ranking.voce': 'YOU',
    'ranking.treinos': 'workouts completed',
    'ranking.vazioTitulo': 'Ranking not available yet',
    'ranking.vazioTexto': 'Come back later to check your position.',

    'alimentacao.consumoDiario': 'Daily Consumption',
    'alimentacao.refeicoesHoje': "Today's meals",
    'alimentacao.minhasFotos': 'My photos',
    'alimentacao.semFotos': 'No photos saved yet.',
    'alimentacao.abasFotos': 'Photos',
    'alimentacao.abasAlbuns': 'Albums',
    'alimentacao.abasHistorias': 'Stories',
    'alimentacao.abasMais': 'More',
    'alimentacao.permissaoTitulo': 'Permission required',
    'alimentacao.permissaoMsg': 'We need access to your photos to save your progress.',
    'alimentacao.erroSalvarFoto': 'Could not save the photo.',
    'alimentacao.cameraIndisponivel': 'Camera unavailable',
    'alimentacao.cameraMsg': 'Open the device settings to allow camera access.',
    'alimentacao.cameraPermMsg': 'We need the camera to record your meal.',
    'alimentacao.erroCapturar': 'Could not capture the image.',

    'batimento.aguardando': 'Waiting...',
    'batimento.altaPrecisao': '🟢 High accuracy',
    'batimento.mediaPrecisao': '🟡 Medium accuracy',
    'batimento.baixaPrecisao': '🔴 Low accuracy',
    'batimento.queimaDiaria': 'DAILY BURN',
    'batimento.localizacao': 'LOCATION',
    'batimento.atualizar': 'Refresh',
    'batimento.buscando': 'Searching...',
    'batimento.precisao': 'Accuracy:',
    'batimento.precisaoAnalise': 'Calculating accuracy',
    'batimento.erroBloqueadoTitulo': 'Location blocked',
    'batimento.erroBloqueadoMsg': 'Open the device settings to allow GPS use.',
    'batimento.erroPermissao': 'Location permission denied.',
    'batimento.erroGps': 'GPS is off. Turn on location to continue.',
    'batimento.erroObter': 'Could not get your location right now.',

    'calorias.batimentoCardiaco': 'HEART RATE',
    'calorias.normal': 'Normal',
    'calorias.de': 'of',

    'mensal.mensal': 'Monthly',
    'mensal.anual': 'Annual',
    'mensal.eterno': 'Forever',
    'mensal.cobradoMensalmente': 'Billed monthly',
    'mensal.cobradoAnualmente': 'Billed annually',
    'mensal.compraUnica': 'One-time purchase',
    'mensal.benef1Titulo': 'Unlimited routines',
    'mensal.benef1Desc': 'Create any routine you want',
    'mensal.benef2Titulo': '10 AI tokens every day',
    'mensal.benef2Desc': 'Build workouts with AI assistance',
    'mensal.benef3Titulo': 'Advanced statistics',
    'mensal.benef3Desc': 'Track your progress in detail',
    'mensal.benef4Titulo': 'Support our team',
    'mensal.benef4Desc': 'Help GymVance keep improving',
    'mensal.assinar': 'Subscribe',
    'mensal.agoraNao': 'Not now',
    'mensal.ativadoTitulo': 'PRO plan activated',
    'mensal.ativadoMsg': 'Your {plano} plan was selected successfully.',
    'mensal.erroAtivar': 'Could not activate the plan right now.',

    'configuracoes.perfil': 'Profile',
    'configuracoes.conta': 'Account',
    'configuracoes.unidade': 'Units',
    'configuracoes.faq': 'FAQ',
    'configuracoes.avaliar': 'Rate App',
    'configuracoes.treinos': 'Workouts',
    'configuracoes.pro': 'PRO',
    'configuracoes.versao': 'Version',

    'perfil.seguidores': 'Followers',
    'perfil.seguindo': 'Following',
    'perfil.estatisticas': 'Statistics',
    'perfil.exercicios': 'Exercises',
    'perfil.medidas': 'Measurements',
    'perfil.calendario': 'Calendar',
    'perfil.bio': 'Bio',
    'perfil.idade': 'Age',
    'configuracoes.perfilTitulo': 'Profile Settings',

    'editarPerfil.titulo': 'Edit Profile',
    'editarPerfil.nome': 'Name',
    'editarPerfil.placeholderNome': 'Enter your name',
    'editarPerfil.bio': 'Bio',
    'editarPerfil.placeholderBio': 'Tell us about yourself',
    'editarPerfil.genero': 'Gender',
    'editarPerfil.idade': 'Age',
    'editarPerfil.foto': 'Profile Photo',
    'editarPerfil.alterarFoto': 'Change Photo',
    'editarPerfil.removerFoto': 'Remove Photo',
    'editarPerfil.salvar': 'Save Changes',

    'conta.titulo': 'Account',
    'conta.nome': 'Name',
    'conta.email': 'Email',
    'conta.senha': 'Password',
    'conta.novaSenha': 'New Password',
    'conta.confirmarSenha': 'Confirm New Password',
    'conta.senhaAtual': 'Current Password',
    'conta.alterarSenha': 'Change Password',
    'conta.salvar': 'Save Changes',
    'conta.erroSenhaAtual': 'Current password is incorrect',
    'conta.erroSenhasDiferentes': 'New passwords do not match',
    'conta.erroSenhaCurta': 'New password must be at least 6 characters',
    'conta.sucesso': 'Changes saved successfully',

    'unidade.titulo': 'Unit of Measure',
    'unidade.peso': 'Weight',
    'unidade.altura': 'Height',
    'unidade.kg': 'kg',
    'unidade.lb': 'lb',
    'unidade.cm': 'cm',
    'unidade.ft': 'ft/in',

    'faq.titulo': 'Frequently Asked Questions',
    'faq.categoria.conta': 'Account & Profile',
    'faq.categoria.treinos': 'Workouts',
    'faq.categoria.pro': 'PRO',
    'faq.categoria.idioma': 'Language & Units',
    'faq.categoria.app': 'App Functionality',
    'faq.pergunta1': 'How do I change my name or profile photo?',
    'faq.resposta1': 'Go to Settings > Profile and tap the photo or the Edit Profile button.',
    'faq.pergunta2': 'How do I change my email or password?',
    'faq.resposta2': 'Go to Settings > Account to change your login credentials.',
    'faq.pergunta3': 'Are my workouts saved automatically?',
    'faq.resposta3': 'Yes, when you finish a session in "Active Session", the workout is saved to local history.',
    'faq.pergunta4': 'How does the PRO plan work?',
    'faq.resposta4': 'The PRO plan unlocks unlimited routines, daily AI tokens, advanced statistics, and supports app development.',
    'faq.pergunta5': 'How do I change the app language?',
    'faq.resposta5': 'Go to Settings > Language and select Portuguese or English.',
    'faq.pergunta6': 'Can I use pounds (lb) instead of kg?',
    'faq.resposta6': 'Yes, in Settings > Units you can change weight and height preferences.',
    'faq.pergunta7': 'Does the app work offline?',
    'faq.resposta7': 'Yes, all data is saved locally on your device.',
    'faq.pergunta8': 'How do I contact support?',
    'faq.resposta8': 'Email support@gymvance.com',

    'avaliar.titulo': 'Rate Application',
    'avaliar.subtitulo': 'Your feedback helps us improve GymVance',
    'avaliar.botao': 'Rate on Play Store',
    'avaliar.obrigado': 'Thank you for rating!',
    'avaliar.erro': 'Could not open store. Please try again later.',

    'treinos.titulo': 'My Workouts',
    'treinos.irParaTreino': 'Go to workout area',

    'exercicios.titulo': 'Exercise Catalog',
    'exercicios.pesquisar': 'Search exercise...',
    'exercicios.categoria.maquinas': 'Machines',
    'exercicios.categoria.cabos': 'Cables / Pulleys',
    'exercicios.categoria.pesosLivres': 'Free Weights',
    'exercicios.categoria.pesoCorporal': 'Bodyweight / Free',
    'exercicios.categoria.personalizados': 'Custom',

    'exercicios.grupo.peito': 'Chest',
    'exercicios.grupo.costas': 'Back',
    'exercicios.grupo.ombros': 'Shoulders',
    'exercicios.grupo.biceps': 'Biceps',
    'exercicios.grupo.triceps': 'Triceps',
    'exercicios.grupo.pernas': 'Legs',
    'exercicios.grupo.gluteos': 'Glutes',
    'exercicios.grupo.panturrilhas': 'Calves',
    'exercicios.grupo.abdomen': 'Abs',
    'exercicios.grupo.corpointeiro': 'Full Body',

    'exercicios.oficial': 'Official',
    'exercicios.personalizado': 'Custom',
    'exercicios.criarPersonalizado': '+ Create custom exercise',
    'exercicios.semResultados': 'No exercises found',
    'exercicios.adicionar': 'Add to session',
    'exercicios.selecionarGrupo': 'Select a muscle group',
    'exercicios.editarTitulo': 'Edit custom exercise',
    'exercicios.editar': 'Edit',
    'exercicios.excluir': 'Delete',
    'exercicios.excluirTitulo': 'Delete exercise',
    'exercicios.excluirMsg': 'Delete this custom exercise? This action cannot be undone.',

    'calendario.titulo': 'Workout Calendar',
    'calendario.verCalendario': 'View calendar',
    'calendario.treinosMes': '{treinos} workouts this month',
    'calendario.semTreinosMes': 'No workouts this month',
    'calendario.semTreinosDia': 'No workouts on this day',
    'calendario.mesAnterior': 'Previous month',
    'calendario.proximoMes': 'Next month',
    'calendario.exercicios': '{count} exercises',
    'calendario.diaSemana.0': 'S',
    'calendario.diaSemana.1': 'M',
    'calendario.diaSemana.2': 'T',
    'calendario.diaSemana.3': 'W',
    'calendario.diaSemana.4': 'T',
    'calendario.diaSemana.5': 'F',
    'calendario.diaSemana.6': 'S',
    'calendario.mes.0': 'January',
    'calendario.mes.1': 'February',
    'calendario.mes.2': 'March',
    'calendario.mes.3': 'April',
    'calendario.mes.4': 'May',
    'calendario.mes.5': 'June',
    'calendario.mes.6': 'July',
    'calendario.mes.7': 'August',
    'calendario.mes.8': 'September',
    'calendario.mes.9': 'October',
    'calendario.mes.10': 'November',
    'calendario.mes.11': 'December',

    'sessaoAtiva.retomarTitulo': 'Workout in progress',
    'sessaoAtiva.retomarMsg': 'There is an unfinished workout saved on this device. Do you want to continue where you left off?',
    'sessaoAtiva.continuarTreino': 'Resume workout',
    'sessaoAtiva.comecarNovo': 'Start a new session',

    'perfil.ofensiva': 'Streak',

    'perfil.exerciciosUnicos': 'Unique exercises performed',
    'perfil.calendarioEmBreve': 'Workout calendar coming soon',
    'comum.anos': 'years',
    'exercicios.grupoMuscular': 'Muscle Group',
    'exercicios.equipamento': 'Equipment',
    'novaSessao.adicionarExercicio': 'Add Exercise',
    'novaSessao.exerciciosDaSessao': 'Session Exercises',
    'novaSessao.erroSemExercicios': 'Add at least one exercise',
    'novaSessao.erroSemTitulo': 'Add a session title',
    'novaSessao.iniciarTreino': 'Start Workout',
    'exercicios.equipamentoPlaceholder': 'Ex: Dumbbells, Machine, Bodyweight',
    'exercicios.equipamento.maquina': 'Machine',
    'exercicios.equipamento.cabo': 'Cable',
    'exercicios.equipamento.barra': 'Barbell',
    'exercicios.equipamento.halteres': 'Dumbbells',
    'exercicios.equipamento.halter': 'Dumbbell',
    'exercicios.equipamento.pesoCorporal': 'Bodyweight',
    'exercicios.equipamento.paralelas': 'Parallel bars',
    'exercicios.equipamento.personalizado': 'Custom',
   },
 };

function traduzir(dicionario, chave, params) {
  if (!Object.prototype.hasOwnProperty.call(dicionario, chave)) {
    return chave;
  }
  let texto = dicionario[chave];
  if (params) {
    Object.keys(params).forEach((nome) => {
      texto = texto.replace(new RegExp(`\\{${nome}\\}`, 'g'), String(params[nome]));
    });
  }
  return texto;
}

export function removerAcentos(texto) {
  return String(texto || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

export function chaveTraducaoGrupoMuscular(grupo) {
  return `exercicios.grupo.${removerAcentos(grupo).toLowerCase().replace(/\s+/g, '')}`;
}

const EQUIPAMENTO_CHAVE = {
  'Máquina': 'exercicios.equipamento.maquina',
  'Cabo': 'exercicios.equipamento.cabo',
  'Barra': 'exercicios.equipamento.barra',
  'Halteres': 'exercicios.equipamento.halteres',
  'Halter': 'exercicios.equipamento.halter',
  'Peso Corporal': 'exercicios.equipamento.pesoCorporal',
  'Paralelas': 'exercicios.equipamento.paralelas',
  'Personalizado': 'exercicios.equipamento.personalizado',
};

export function chaveTraducaoEquipamento(equipamento) {
  return EQUIPAMENTO_CHAVE[equipamento] || equipamento;
}

const IdiomaContext = createContext({
  idioma: 'pt',
  definirIdioma: () => {},
  t: (chave) => chave,
  numero: (valor) => String(valor ?? 0),
});

export function IdiomaProvider({ children }) {
  const [idioma, setIdiomaEstado] = useState('pt');

  useEffect(() => {
    let ativo = true;

    getLanguage().then((salvo) => {
      if (ativo && salvo) {
        setIdiomaEstado(salvo);
      }
    });

    return () => {
      ativo = false;
    };
  }, []);

  const definirIdioma = useCallback((novo) => {
    const limpo = novo === 'en' ? 'en' : 'pt';
    setIdiomaEstado(limpo);
    setLanguageStorage(limpo);
  }, []);

  const t = useCallback(
    (chave, params) => {
      const en = TRADUCOES.en;
      const pt = TRADUCOES.pt;
      const dicionario = idioma === 'en' ? en : pt;
      const direto = traduzir(dicionario, chave, params);
      if (direto !== chave) {
        return direto;
      }
const emIngles = traduzir(en, chave, params);
      if (emIngles !== chave) {
        return emIngles;
      }
      return chave;
    },
    [idioma]
  );

  const numero = useCallback(
    (valor) => {
      if (valor === null || valor === undefined) {
        return '—';
      }
      return Number(valor).toLocaleString(idioma === 'pt' ? 'pt-BR' : 'en-US');
    },
    [idioma]
  );

  return (
    <IdiomaContext.Provider value={{ idioma, definirIdioma, t, numero }}>
      {children}
    </IdiomaContext.Provider>
  );
}

export function useIdioma() {
  return useContext(IdiomaContext);
}